### ISSUE TITLE
Suggest adding Markdown file containing scripts

### ISSUE THREAD

**Issue by pcarbo** [heejungshim/prepare-summary-data-from-subfraction-analysis#1]
This will make your code more accessible on github, I think. See attached Markdown file.

I used Pandoc to create this file from your Latex:

```bash
pandoc -f latex -t markdown prepareData.tex > prepareData.md
```

[prepareData.md.zip](https://github.com/heejungshim/prepare-summary-data-from-subfraction-analysis/files/634351/prepareData.md.zip)

**Comment by heejungshim** [comment]
Peter, I just added this markdown file to github. Thanks!
